project/dashboard/forms.py
# encoding: utf-8
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField, IntegerField, DecimalField
from wtforms.validators import DataRequired, Length
from datetime import datetime


class CreateForm(FlaskForm):
	instance_name = StringField(u'实例名称', validators=[DataRequired(), Length(1, 128)])
	CPUsize = DecimalField(u'cpu大小', validators=[DataRequired()])
	MEMsize = DecimalField(u'内存大小', validators=[DataRequired()])
	insScale = IntegerField(u'实例规模', validators=[DataRequired()])
	GPUnum = IntegerField(u'gpu数量', validators=[DataRequired()])
	isSSD = BooleanField(u'是否使用SSD', validators=[DataRequired()])
	submit = SubmitField(u'提交')


class UpdateForm(FlaskForm):
	new_scale = DecimalField(u'实例规模', validators=[DataRequired()])
	submit = SubmitField(u'提交')

class QueryForm(FlaskForm):
	instance_id = IntegerField(u'实例ID', validators=[DataRequired()])
	submit = SubmitField(u'提交')

class DeleteForm(FlaskForm):
	instance_id = IntegerField(u'实例ID', validators=[DataRequired()])
	submit = SubmitField(u'提交')

project/dashboard/__init__.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-

from flask import Blueprint

dashboard = Blueprint('dashboard', __name__)

from . import routes

project/dashboard/routes.py
# encoding: utf-8
from flask import render_template, flash, redirect, url_for, abort, request, current_app, g, jsonify
from datetime import datetime
from flask_login import login_required, current_user
from .. import db
from ..models import User
from .forms import CreateForm, UpdateForm, DeleteForm, QueryForm
from ..util.API_manage import ApiClient
from . import dashboard
import json

@dashboard.route('/home/<int:userid>', methods=['GET', 'POST'])
@login_required
def home(userid):
	login_data = dict(name = current_user.name, id = current_user.id)

	#  TODO: replace debug code with api_client
	#
	#  ==========================================================================
	# api_client = ApiClient(login_data=login_data)
	# api_client.login()
	# data = api_client.get_instances_list()
	# #ins_list type: 'dict' in 'list'
	# ins_list = [dict(name = ins.name, id = ins.id, is_deleted = ins.is_deleted, update_time = ins.update_time)\
	# 			 for ins in json.loads(data)['ins_list']]
	#  ==========================================================================

	# WARNING: This is an example for the api_client function,need to be replaced;
	# ===========================================================================
	ins_list = [dict(name = "test.name1", id = 1, is_deleted = False, update_time = 100)]
	# ===========================================================================
	return render_template('dashboard/home.html',
							userid=userid,
							ins_list = ins_list)

@dashboard.route('/detail/<int:iid>', methods=['GET', 'POST'])
@login_required
def detail(iid):
	login_data = dict(name = current_user.name, id = current_user.id)
	#  TODO: replace debug code with api_client
	#
	#  ==========================================================================
	# api_client = ApiClient(login_data=login_data)
	# api_client.login()
	# data = api_client.get_instance_detail(iid=iid)
	#  ==========================================================================

	# WARNING: This is an example for the api_client function,need to be replaced;
	#  ==========================================================================
	data = dict(id = 1,name = "instance_test_name",\
		CPUsize = 10,MEMsize = 1024.0,GPUnum = 10,scale = 10,\
		isSSD = True,postStamp = 10000,serviceIP = "127.0.0.1",\
		servicePort = 10086,updateStamp = 10020,deleteStamp = 20000)
	#  ==========================================================================

	return render_template("dashboard/detail.html",
							userid = current_user.id,iid = iid,data = data)


@dashboard.route('/create', methods=['GET','POST'])
@login_required
def create():
	form = CreateForm()
	if form.validate_on_submit():
		login_data = dict(name = current_user.name, id = current_user.id)
		# TODO: replace debug code with api_client
		# =============================================================================
		# api_client = ApiClient(login_data=login_data)
		# api_client.login()
		# r_status = api_client.create_instance(name = form.instance_name.data,
		# 									cpu = form.CPUsize.data,
		# 									mem = form.MEMsize.data,
		# 									scale = form.insScale.data,
		# 									gpu = form.GPUnum.data,
		# 									isSSD = form.isSSD.data)
		# if r_status == 200:
		# 	flash('created')
		# 	return redirect(url_for('.home'))
		# =============================================================================

	return render_template('dashboard/create.html',userid = current_user.id, form=form)

@dashboard.route('/update/<int:iid>', methods=['POST', 'GET'])
@login_required
def update(iid):
	form = UpdateForm()
	if form.validate_on_submit():
		login_data = dict(name = current_user.name, id = current_user.id)
		# TODO: replace debug code with api_client
		# =============================================================================
		# api_client = ApiClient(login_data=login_data)
		# api_client.login()
		# r_status = api_client.update_instance(iid=iid, new_scale = form.new_scale.data)
		# if r_status == 200:
		# 	flash('updated')
		# 	return redirect(url_for('.home'))
		# =============================================================================

		# WARNING: This is an example for the api_client function,need to be replaced;
		#  ==========================================================================

		#  ==========================================================================

	return render_template('dashboard/update.html',userid = current_user.id, iid = iid, form=form)

@dashboard.route('/delete/<int:iid>', methods=['POST'])
@login_required
def delete(iid):
	form = DeleteForm()
	if form.validate_on_submit():
		login_data = dict(name = current_user.name, id = current_user.id)
		# TODO: replace debug code with api_client
		# =============================================================================
		# api_client = ApiClient(login_data=login_data)
		# api_client.login()
		# r_status = api_client.delete_instance(iid=iid)
		# if r_status == 200:
		# 	flash(str('instance ID = '  + str(iid)  + ' has been deleted'))
		# 	return redirect(url_for('.home',userid = current_user.id))
		# =============================================================================

	# WARNING: This is an example for the api_client function,need to be replaced;
	#  ==========================================================================
	flash(str('instance ID = '  + str(iid)  + ' has been deleted'))
	return redirect(url_for('.home',userid = current_user.id))
	#  ==========================================================================

project/templates/dashboard/create.html
{% extends "layout.html" %}
{% block body %}
{% import "bootstrap/wtf.html" as wtf %}
<div class="container">
  <div class="raw">
    <h2>Home <small>当前用户ID：{{userid}}</small></h1>
    <div class="col-md-6 col-md-offset-3">
      {{ wtf.quick_form(form) }}
    </div>
  </div>
</div>
{% endblock %}

project/templates/dashboard/detail.html
{% extends "layout.html" %} {% block body %}
<div class="page-header">
  <div class="container">
    <div class="raw">
      <h2>Home <small>当前用户ID：{{userid}} </small></h1>
      <div class="col-md-10 col-md-offset-1">
        <h3>任务ID:{{iid}}</h3>
        <table class="table table-striped table-hover ">
          <tr>
            <th>id</th>
            <td>{{data['id']}}</td>
          </tr>
          <tr>
            <th>name</th>
            <td>{{data['name']}}</td>
          </tr>
          <tr>
            <th>CPUsize</th>
            <td>{{data['CPUsize']}}</td>
          </tr>
          <tr>
            <th>MEMsize</th>
            <td>{{data['MEMsize']}}</td>
          </tr>
          <tr>
            <th>GPUnum</th>
            <td>{{data['GPUnum']}}</td>
          </tr>
          <tr>
            <th>scale</th>
            <td>{{data['scale']}}</td>
          </tr>
          <tr>
            <th>isSSD</th>
            <td>{{data['isSSD']}}</td>
          </tr>
          <tr>
            <th>postStamp</th>
            <td>{{data['postStamp']}}</td>
          </tr>
          <tr>
            <th>serviceIP</th>
            <td>{{data['serviceIP']}}</td>
          </tr>
          <tr>
            <th>servicePort</th>
            <td>{{data['servicePort']}}</td>
          </tr>
          <tr>
            <th>updateStamp</th>
            <td>{{data['updateStamp']}}</td>
          </tr>
          <tr>
            <th>deleteStamp</th>
            <td>{{data['deleteStamp']}}</td>
          </tr>
          <tr>
            <th>option</th>
            <td>
              <div class="btn-group btn-group-justified" >
                <div class="btn-group">
                  <form action={{url_for("dashboard.update",iid = iid)}} method="get" id="form1">
                    <button type="button" class="btn btn-md btn-warning" onclick="submit(form1)" style="width: 108px !important;">Update</button>
                  </form>
                </div>
              <div class="btn-group">
                <form action={{url_for("dashboard.delete",iid = iid)}} method="post" id="form2" style="width: 108px !important;">
                  <button type="button" class="btn btn-md btn-danger" onclick="submit(form2)">Delete</button>
                </form>
              </div>
            </div>
          </td>
        </tr>
      </div>
    </div>
  </div>
</div>


{% endblock %}

project/templates/dashboard/home.html
{% extends "layout.html" %} {% block body %}
<div class="page-header">
  <div class="container">
    <div class="raw">
      <h2>Home <small>当前用户ID：{{userid}}</small></h1>
      <div class="col-md-10 col-md-offset-1">
        <h3>任务列表</h3>
        <table class="table table-striped table-hover ">
          <tr>
            <th>name</th>
            <th>id</th>
            <th>is_deleted</th>
            <th>update_time</th>
            <th width=20%>option</th>
          </tr>
          {% for ins in ins_list %}
          <tr>
            <td>{{ins['name']}}</td>
            <td>{{ins['id']}}</td>
            <td>{{ins['is_deleted']}}</td>
            <td>{{ins['update_time']}}</td>
            <td>
              <a href={{url_for("dashboard.detail",iid = ins['id'])}}>查看详情</a>
            </td>
          </tr>
          {% endfor %}
      </div>
    </div>
  </div>
</div>

{% endblock %}

project/templates/dashboard/update.html
{% extends "layout.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block body %}

<div class="container">
  <div class="raw">
    <h2>Home <small>当前用户ID：{{userid}}</small></h1>
    <div class="col-md-6 col-md-offset-3">
      {{ wtf.quick_form(form) }}
    </div>
  </div>
</div>

{% endblock %}